#
# Generate Docker secrets files from .env.secrets
#
# This script reads secrets from .env.secrets and creates individual
# secret files in docker/secrets/ directory for use with Docker secrets.
#
# Usage: .\secrets.ps1

$ErrorActionPreference = "Stop"

$SECRETS_FILE = ".env.secrets"
$SECRETS_DIR = "docker/secrets"
$SECRETS_ENV_FILE = "docker/.env.secrets.docker"

# Check if .env.secrets exists
if (-not (Test-Path $SECRETS_FILE)) {
    Write-Error "Error: $SECRETS_FILE not found!"
    Write-Host "Please create $SECRETS_FILE from .env.secrets.example"
    exit 1
}

# Create secrets directory if it doesn't exist
if (-not (Test-Path $SECRETS_DIR)) {
    New-Item -ItemType Directory -Path $SECRETS_DIR | Out-Null
}

Write-Host "Generating Docker secret files from $SECRETS_FILE..."

# Read .env.secrets and create individual secret files
Get-Content $SECRETS_FILE | ForEach-Object {
    $line = $_.Trim()
    
    # Skip empty lines and comments
    if ([string]::IsNullOrWhiteSpace($line) -or $line.StartsWith('#')) {
        return
    }
    
    # Split on first = only
    $parts = $line -split '=', 2
    if ($parts.Length -ne 2) {
        return
    }
    
    $key = $parts[0].Trim()
    $value = $parts[1].Trim()
    
    # Convert environment variable name to secret filename
    # e.g., SESSION_SECRET -> session_secret.txt
    $secret_name = $key.ToLower()
    $secret_file = Join-Path $SECRETS_DIR "$secret_name.txt"
    
    # Write value to secret file
    Set-Content -Path $secret_file -Value $value -NoNewline
    
    # Set file permissions (Windows equivalent of chmod 600)
    $acl = Get-Acl $secret_file
    $acl.SetAccessRuleProtection($true, $false)
    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        [System.Security.Principal.WindowsIdentity]::GetCurrent().Name,
        "FullControl",
        "Allow"
    )
    $acl.SetAccessRule($rule)
    Set-Acl $secret_file $acl
    
    Write-Host "  Created: $secret_file"
}

Write-Host ""
Write-Host "Generating Docker Compose environment file for secret paths..."

# Create .env.secrets.docker file with _FILE environment variables
$envContent = @"
# Auto-generated file - DO NOT EDIT MANUALLY
# Generated by secrets.ps1 script
#
# These environment variables tell database containers to read passwords
# from Docker secret files instead of direct environment variables.
# This file is only used when Docker secrets are enabled.

# Main application database
POSTGRES_PASSWORD_FILE=/run/secrets/database_password

# Keycloak SSO service
KEYCLOAK_ADMIN_PASSWORD_FILE=/run/secrets/keycloak_admin_password
KC_DB_PASSWORD_FILE=/run/secrets/keycloak_database_password

# Keycloak database
KC_DB_POSTGRES_PASSWORD_FILE=/run/secrets/keycloak_database_password

# Nominatim geocoding service
NOMINATIM_POSTGRES_PASSWORD_FILE=/run/secrets/nominatim_database_password

# BookStack wiki database
MYSQL_ROOT_PASSWORD_FILE=/run/secrets/bookstack_root_password
MYSQL_PASSWORD_FILE=/run/secrets/bookstack_database_password
"@

Set-Content -Path $SECRETS_ENV_FILE -Value $envContent

# Set file permissions
$acl = Get-Acl $SECRETS_ENV_FILE
$acl.SetAccessRuleProtection($true, $false)
$rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    [System.Security.Principal.WindowsIdentity]::GetCurrent().Name,
    "FullControl",
    "Allow"
)
$acl.SetAccessRule($rule)
Set-Acl $SECRETS_ENV_FILE $acl

Write-Host "  Created: $SECRETS_ENV_FILE"

Write-Host ""
Write-Host "Docker secrets generated successfully!"
Write-Host ""
Write-Host "Secret files location: $SECRETS_DIR/"
Write-Host "Docker Compose env file: $SECRETS_ENV_FILE"
Write-Host ""
Write-Host "To use secrets, ensure docker-compose reads the .env.secrets.docker file:"
Write-Host "  docker compose --env-file docker/.env.secrets.docker up -d"
Write-Host ""
Write-Host "Or add to your docker-compose.yml services that need it:"
Write-Host "  env_file:"
Write-Host "    - .env.secrets.docker"
