{
 "title": "PNNL ROB - rtu01 Overview",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Outdoor Air Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"OutdoorAirTemperature\" from data natural join topics where topic_name like 'PNNL/ROB/%/OutdoorAirTemperature' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Zone Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"ZoneHumidity\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/ZoneHumidity' AND $__timeFilter(ts) ORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Zone Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"Zone Temperature\" from data natural join topics where topic_name like 'PNNL/ROB/%' and topic_name like '%/rtu01/ZoneTemperature' AND $__timeFilter(ts) ORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Setpoints",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"Heating SP\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/OccupiedHeatingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"Cooling SP\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/OccupiedCoolingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"Unocc Heat SP\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/UnoccupiedHeatingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"Unocc Cool SP\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/UnoccupiedCoolingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Occupancy Command",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"Occupancy\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/OccupancyCommand' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Heating Command",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"Heating Command\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/FirstStageHeating' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Supply Fan",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"Supply Fan\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/SupplyFanStatus' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Cooling Stage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(ts, '1m') AS \"time\",\r\n  SUM(CAST(NULLIF(value_string, 'null') AS double precision)) AS \"CoolingStage\"\r\nFROM data\r\nNATURAL JOIN topics\r\nWHERE topic_name LIKE 'PNNL/ROB/rtu01/%StageCooling'\r\n  AND $__timeFilter(ts)\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "rtu01",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"OccupiedCoolingSetPoint\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/OccupiedCoolingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"OccupiedHeatingSetPoint\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/OccupiedHeatingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"FirstStageHeating\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/FirstStageHeating' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"SupplyFanStatus\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/SupplyFanStatus' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"ZoneHumidity\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/ZoneHumidity' AND $__timeFilter(ts) ORDER BY 1;\r\n"
    },
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"ZoneTemperature\" from data natural join topics where topic_name like 'PNNL/ROB/%' and topic_name like '%/rtu01/ZoneTemperature' AND $__timeFilter(ts) ORDER BY 1;\r\n"
    },
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"OutdoorAirTemperature\" from data natural join topics where topic_name like 'PNNL/ROB/%/OutdoorAirTemperature' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"OccupancyCommand\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/OccupancyCommand' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroup(ts, '1m') AS \"time\",\r\n  SUM(CAST(NULLIF(value_string, 'null') AS double precision)) AS \"CoolingStage\"\r\nFROM data\r\nNATURAL JOIN topics\r\nWHERE topic_name LIKE 'PNNL/ROB/rtu01/%StageCooling'\r\n \r\n  AND $__timeFilter(ts)\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    },
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"UnoccupiedCoolingSetPoint\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/UnoccupiedCoolingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", CAST(NULLIF(value_string, 'null') AS double precision) as \"UnoccupiedHeatingSetPoint\" from data natural join topics where topic_name like 'PNNL/ROB/rtu01/UnoccupiedHeatingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  }
 ]
}