compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules

# Registry configuration with fallbacks
npmRegistryServer: "https://registry.npmjs.org"
npmAlwaysAuth: false

# Network optimization settings
httpTimeout: 60000
networkConcurrency: 8

# Retry configuration for VPN scenarios
httpRetry: 3

# Connection optimization
httpProxy: ${HTTP_PROXY-}
httpsProxy: ${HTTPS_PROXY-}

# Compression and caching
enableNetwork: true
enableOfflineMode: false

# Performance optimizations
preferInteractive: false
progressBarStyle: patrick
