#!/bin/sh
#
# Generate Docker secrets files from .env.secrets
#
# This script reads secrets from .env.secrets and creates individual
# secret files in docker/secrets/ directory for use with Docker secrets.
#
# Usage: ./secrets.sh

set -e

SECRETS_FILE=".env.secrets"
SECRETS_DIR="docker/secrets"
SECRETS_ENV_FILE="docker/.env.secrets.docker"

# Check if .env.secrets exists
if [ ! -f "$SECRETS_FILE" ]; then
  echo "Error: $SECRETS_FILE not found!"
  echo "Please create $SECRETS_FILE from .env.secrets.example"
  exit 1
fi

# Create secrets directory if it doesn't exist
mkdir -p "$SECRETS_DIR"

echo "Generating Docker secret files from $SECRETS_FILE..."

# Read .env.secrets and create individual secret files
while IFS= read -r line || [ -n "$line" ]; do
  # Skip empty lines and comments
  case "$line" in
    ''|\#*) continue ;;
  esac

  # Split on the FIRST = only so values containing = are preserved intact
  key=$(printf '%s' "$line" | sed 's/=.*//')
  value=$(printf '%s' "$line" | sed 's/^[^=]*=//')

  # Remove leading/trailing whitespace from key and value
  key=$(printf '%s' "$key" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  value=$(printf '%s' "$value" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  
  # Convert environment variable name to secret filename
  # e.g., SESSION_SECRET -> session_secret.txt
  secret_name=$(echo "$key" | tr '[:upper:]' '[:lower:]')
  secret_file="$SECRETS_DIR/${secret_name}.txt"

  # `docker compose up` will auto-create the mount source as a directory when
  # the declared secret file is missing, leaving a broken `./secrets/foo.txt/`
  # directory that later blocks `echo ... > $secret_file`. Recover from that
  # state here: remove an empty directory at the target, refuse on a
  # non-empty one so we never destroy user data.
  if [ -d "$secret_file" ]; then
    if [ -z "$(ls -A "$secret_file" 2>/dev/null)" ]; then
      rmdir "$secret_file"
    else
      echo "Error: $secret_file exists as a non-empty directory." >&2
      echo "Refusing to overwrite. Move or delete it manually, then re-run." >&2
      exit 1
    fi
  fi

  # Write value to secret file
  echo "$value" > "$secret_file"
  chmod 600 "$secret_file"
  
  echo "  Created: $secret_file"
done < "$SECRETS_FILE"

echo ""
echo "Generating Docker Compose environment file for secret paths..."

# Create .env.secrets.docker file with _FILE environment variables
cat > "$SECRETS_ENV_FILE" << 'EOF'
# Auto-generated file - DO NOT EDIT MANUALLY
# Generated by secrets.sh script
#
# These environment variables tell database containers to read passwords
# from Docker secret files instead of direct environment variables.
# This file is only used when Docker secrets are enabled.

# Main application database
POSTGRES_PASSWORD_FILE=/run/secrets/database_password

# Keycloak SSO service
KEYCLOAK_ADMIN_PASSWORD_FILE=/run/secrets/keycloak_admin_password
KC_DB_PASSWORD_FILE=/run/secrets/keycloak_database_password

# Keycloak database
KC_DB_POSTGRES_PASSWORD_FILE=/run/secrets/keycloak_database_password

# Nominatim geocoding service
NOMINATIM_POSTGRES_PASSWORD_FILE=/run/secrets/nominatim_database_password

# BookStack wiki database
MYSQL_ROOT_PASSWORD_FILE=/run/secrets/bookstack_root_password
MYSQL_PASSWORD_FILE=/run/secrets/bookstack_database_password

# Compose top-level `secrets:` entries interpolate `${*_SOURCE}` to pick
# the host-side file. When unset, compose falls back to the tracked
# empty `docker/secrets/.placeholder`. Setting these overrides the
# fallback so real secret files get mounted.
SESSION_SECRET_SOURCE=./secrets/session_secret.txt
JWT_SECRET_SOURCE=./secrets/jwt_secret.txt
DATABASE_PASSWORD_SOURCE=./secrets/database_password.txt
REDIS_PASSWORD_SOURCE=./secrets/redis_password.txt
KEYCLOAK_CLIENT_SECRET_SOURCE=./secrets/keycloak_client_secret.txt
KEYCLOAK_ADMIN_PASSWORD_SOURCE=./secrets/keycloak_admin_password.txt
KEYCLOAK_DATABASE_PASSWORD_SOURCE=./secrets/keycloak_database_password.txt
NOMINATIM_DATABASE_PASSWORD_SOURCE=./secrets/nominatim_database_password.txt
BOOKSTACK_SESSION_SECRET_SOURCE=./secrets/bookstack_session_secret.txt
BOOKSTACK_ROOT_PASSWORD_SOURCE=./secrets/bookstack_root_password.txt
BOOKSTACK_DATABASE_PASSWORD_SOURCE=./secrets/bookstack_database_password.txt
BOOKSTACK_KEYCLOAK_CLIENT_SECRET_SOURCE=./secrets/bookstack_keycloak_client_secret.txt
WORKER_TOKEN_SOURCE=./secrets/worker_token.txt

# Blank the plain-env counterparts. The postgres official image's
# `file_env` helper errors out if BOTH `POSTGRES_PASSWORD` and
# `POSTGRES_PASSWORD_FILE` are set; blanking here lets the `_FILE`
# variables above win cleanly. Compose treats an empty env_file value
# as clearing whatever earlier env_file entries set.
POSTGRES_PASSWORD=
KEYCLOAK_ADMIN_PASSWORD=
KC_DB_PASSWORD=
EOF

chmod 600 "$SECRETS_ENV_FILE"
echo "  Created: $SECRETS_ENV_FILE"

echo ""
echo "Docker secrets generated successfully!"
echo ""
echo "Secret files location: $SECRETS_DIR/"
echo "Docker Compose env file: $SECRETS_ENV_FILE"
echo ""
echo "To use secrets, ensure docker-compose reads the .env.secrets.docker file:"
echo "  docker compose --env-file docker/.env.secrets.docker up -d"
echo ""
echo "Or add to your docker-compose.yml services that need it:"
echo "  env_file:"
echo "    - .env.secrets.docker"
