#!/bin/sh
#
# Generate Docker secrets files from .env.secrets
#
# This script reads secrets from .env.secrets and creates individual
# secret files in docker/secrets/ directory for use with Docker secrets.
#
# Usage: ./secrets.sh

set -e

SECRETS_FILE=".env.secrets"
SECRETS_DIR="docker/secrets"
SECRETS_ENV_FILE="docker/.env.secrets.docker"

# Check if .env.secrets exists
if [ ! -f "$SECRETS_FILE" ]; then
  echo "Error: $SECRETS_FILE not found!"
  echo "Please create $SECRETS_FILE from .env.secrets.example"
  exit 1
fi

# Create secrets directory if it doesn't exist
mkdir -p "$SECRETS_DIR"

echo "Generating Docker secret files from $SECRETS_FILE..."

# Read .env.secrets and create individual secret files
while IFS='=' read -r key value || [ -n "$key" ]; do
  # Skip empty lines and comments
  if [ -z "$key" ] || [ "${key#\#}" != "$key" ]; then
    continue
  fi
  
  # Remove leading/trailing whitespace from key and value
  key=$(echo "$key" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  value=$(echo "$value" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  
  # Convert environment variable name to secret filename
  # e.g., SESSION_SECRET -> session_secret.txt
  secret_name=$(echo "$key" | tr '[:upper:]' '[:lower:]')
  secret_file="$SECRETS_DIR/${secret_name}.txt"
  
  # Write value to secret file
  echo "$value" > "$secret_file"
  chmod 600 "$secret_file"
  
  echo "  Created: $secret_file"
done < "$SECRETS_FILE"

echo ""
echo "Generating Docker Compose environment file for secret paths..."

# Create .env.secrets.docker file with _FILE environment variables
cat > "$SECRETS_ENV_FILE" << 'EOF'
# Auto-generated file - DO NOT EDIT MANUALLY
# Generated by secrets.sh script
#
# These environment variables tell database containers to read passwords
# from Docker secret files instead of direct environment variables.
# This file is only used when Docker secrets are enabled.

# Main application database
POSTGRES_PASSWORD_FILE=/run/secrets/database_password

# Keycloak SSO service
KEYCLOAK_ADMIN_PASSWORD_FILE=/run/secrets/keycloak_admin_password
KC_DB_PASSWORD_FILE=/run/secrets/keycloak_database_password

# Keycloak database
KC_DB_POSTGRES_PASSWORD_FILE=/run/secrets/keycloak_database_password

# Nominatim geocoding service
NOMINATIM_POSTGRES_PASSWORD_FILE=/run/secrets/nominatim_database_password

# BookStack wiki database
MYSQL_ROOT_PASSWORD_FILE=/run/secrets/bookstack_root_password
MYSQL_PASSWORD_FILE=/run/secrets/bookstack_database_password
EOF

chmod 600 "$SECRETS_ENV_FILE"
echo "  Created: $SECRETS_ENV_FILE"

echo ""
echo "Docker secrets generated successfully!"
echo ""
echo "Secret files location: $SECRETS_DIR/"
echo "Docker Compose env file: $SECRETS_ENV_FILE"
echo ""
echo "To use secrets, ensure docker-compose reads the .env.secrets.docker file:"
echo "  docker compose --env-file docker/.env.secrets.docker up -d"
echo ""
echo "Or add to your docker-compose.yml services that need it:"
echo "  env_file:"
echo "    - .env.secrets.docker"
