version: "3.8"

services:

  # Proxy that can be configured for HTTP or HTTPS
  proxy:
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certresolver=${CERT_RESOLVER}
      - --providers.file.directory=/etc/traefik/dynamic
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${ADMIN_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/etc/certs/letsencrypt.json
    container_name: ${COMPOSE_PROJECT_NAME}-proxy
    depends_on:
      init:
        condition: service_completed_successfully
    hostname: proxy
    image: traefik:v2.10
    labels:
      - traefik.tls.stores.default.defaultgeneratedcert.resolver=${CERT_RESOLVER}
      - traefik.tls.stores.default.defaultgeneratedcert.domain.main=${HOSTNAME}
      - traefik.tls.stores.default.defaultgeneratedcert.domain.sans=*.${HOSTNAME}
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    profiles:
      - proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/:/etc/certs/
      - ./certs-traefik.yml:/etc/traefik/dynamic/certs-traefik.yml

  # Application that hosts static files and API
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-app
    depends_on:
      init:
        condition: service_completed_successfully
      database:
        condition: service_started
    environment:
      - PORT=3000
      - CLUSTER_TYPE=app
      - LOG_TRANSPORTS=${LOGGERS}
      - LOG_FILE_PATH=./data/app.log
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_SCHEMA=public
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - OSM_HOST=osm
      - OSM_PORT=80
      - AUTH_PROVIDERS=${AUTHENTICATION}
      - PASSWORD_STRENGTH=${PASSWORD_STRENGTH}
      - PASSWORD_VALIDATE=${PASSWORD_VALIDATE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
      - ONEID_CLIENT_ID=${ONEID_CLIENT_ID}
      - ONEID_CLIENT_SECRET=${ONEID_CLIENT_SECRET}
      - ONEID_REDIRECT_URI=${ONEID_REDIRECT_URI}
      - NOMINATIM_PRIVATE_API_URL=${NOMINATIM_PRIVATE_API_URL}
    healthcheck:
      test: "curl --fail http://localhost:3000 || exit 1"
      interval: 10s
      timeout: 10s
      retries: 120
    hostname: app
    image: nextapp:${TAG}
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.security.headers.browserXssFilter=true
      - traefik.http.middlewares.security.headers.contentTypeNosniff=true
      - traefik.http.middlewares.security.headers.forceSTSHeader=true
      - traefik.http.middlewares.security.headers.frameDeny=true
      - traefik.http.middlewares.security.headers.referrerPolicy=same-origin
      - traefik.http.middlewares.security.headers.sslRedirect=true
      - traefik.http.middlewares.security.headers.stsSeconds=31536000
      - traefik.http.services.nextapp.loadbalancer.server.port=3000
      - traefik.http.routers.hostname-http.entrypoints=web
      - traefik.http.routers.hostname-http.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.hostname-http.middlewares=hostname-https
      - traefik.http.middlewares.hostname-https.redirectscheme.scheme=https
      - traefik.http.routers.hostname.entrypoints=websecure
      - traefik.http.routers.hostname.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.hostname.middlewares=security
      - traefik.http.routers.hostname.tls=true
      - traefik.http.routers.hostname.tls.certresolver=${CERT_RESOLVER}
    restart: unless-stopped
    volumes:
      - app-data:/app/data
      - app-cache:/app/.next/cache

  # Runs application services
  services:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-services
    depends_on:
      init:
        condition: service_completed_successfully
      database:
        condition: service_started
    environment:
      - CLUSTER_TYPE=services
      - LOG_TRANSPORTS=${LOGGERS}
      - LOG_FILE_PATH=./data/services.log
      - SEED_DATA_PATH=./seed/
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_SCHEMA=public
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - PASSWORD_STRENGTH=${PASSWORD_STRENGTH}
      - PASSWORD_VALIDATE=${PASSWORD_VALIDATE}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
    healthcheck:
      test: "curl http://localhost:3000/api/graphql"
      interval: 10s
      timeout: 10s
      retries: 120
    hostname: services
    image: nextapp:${TAG}
    restart: unless-stopped
    volumes:
      - app-data:/app/data
      - ./seed/:/app/seed/
      - ../aems-edge:/app/aems-edge

  # Creates self-signed TLS certs for localhost and domain and runs relational database migrations on startup
  init:
    build:
      context: ./
      dockerfile: ./init/Dockerfile
    command: >
      bash -c '
        if [ ! -f /etc/certs/mkcert-ca.crt ]; then
          mkcert create-ca \
            --key "/etc/certs/mkcert-ca.key" \
            --cert "/etc/certs/mkcert-ca.crt"
        fi;
        if [ ! -f /etc/certs/mkcert-hostname.crt ]; then
          mkcert create-cert \
            --ca-key "/etc/certs/mkcert-ca.key" \
            --ca-cert "/etc/certs/mkcert-ca.crt" \
            --key "/etc/certs/mkcert-hostname.key" \
            --cert "/etc/certs/mkcert-hostname.crt" \
            --domain "${HOSTNAME}"
        fi;
        cd /app/;
        yarn migrate;
      '
    container_name: ${COMPOSE_PROJECT_NAME}-init
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_HOST=${COMPOSE_PROJECT_NAME}-database
      - DATABASE_PORT=5432
      - DATABASE_SCHEMA=public
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    hostname: init
    image: init:${TAG}
    volumes:
      - ./certs/:/etc/certs/
      - app-data:/data/

  # Application relational database
  database:
    cap_add:
      - SYS_NICE
    container_name: ${COMPOSE_PROJECT_NAME}-database
    environment:
      - PGUSER=${DATABASE_USERNAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 10
    hostname: database
    image: postgis/postgis:16-3.4-alpine
    restart: unless-stopped
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
      - database-data:/var/lib/postgresql/data

  # OSM container for loading data
  osm-setup:
    command: >
      bash -c '
        if [ ! -f /data/database/planet-import-complete ]; then
          ./run.sh import;
        fi;
      '
    container_name: ${COMPOSE_PROJECT_NAME}-setup
    entrypoint: ""
    environment:
      - DOWNLOAD_PBF=${PBF_URL}
      - DOWNLOAD_POLY=${POLY_URL}
    hostname: osm-setup
    image: overv/openstreetmap-tile-server:2.3.0
    profiles:
      - osm
    volumes:
      - osm-data:/data/database/

  # OSM container for generating tiles
  osm:
    command: "run"
    container_name: ${COMPOSE_PROJECT_NAME}-osm
    depends_on:
      osm-setup:
        condition: service_completed_successfully
    environment:
      - UPDATES=enabled
      - REPLICATION_URL=${REPLICATION_URL}
    hostname: osm
    image: overv/openstreetmap-tile-server:2.3.0
    profiles:
      - osm
    restart: unless-stopped
    volumes:
      - osm-data:/data/database/

  # Nominatim container for geocoding
  nominatim:
    container_name: ${COMPOSE_PROJECT_NAME}-nominatim
    environment:
      - PBF_URL=${PBF_URL}
      - REPLICATION_URL=${REPLICATION_URL}
      - NOMINATIM_PASSWORD=${DATABASE_PASSWORD}
      - IMPORT_US_POSTCODES=true
      - IMPORT_WIKIPEDIA=true
      - IMPORT_TIGER_ADDRESSES=true
    hostname: nominatim
    image: mediagis/nominatim:4.4
    profiles:
      - nom
    restart: unless-stopped
    shm_size: 1gb
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main

volumes:
  app-data:
    driver: local
  app-cache:
    driver: local
  database-data:
    driver: local
  osm-data:
    driver: local
  nominatim-data:
    driver: local
