// Backup Prisma types are regenerated by `yarn compile` after schema migration.
import { Injectable, Logger } from "@nestjs/common";
import { Mutation } from "@local/common";
import { SchemaBuilderService } from "../builder.service";
import { BackupObject } from "./object.service";
import { PothosMutation } from "../pothos.decorator";
import { PrismaService } from "@/prisma/prisma.service";
import { BackupDiscoveryService } from "@/services/backup/backup-discovery.service";
import { BackupSubscriptionPublisher } from "@/services/backup/backup-publisher.service";
import { BackupArchiveService } from "@/services/backup/backup-archive.service";
import { BackupDestination, BackupPolicy } from "@prisma/client";

/**
 * BackupMutation - admin-only mutations for backup orchestration.
 *
 * The `downloadBackupPrivateKey` mutation is intentionally rate-limited to
 * at most one call per minute per user and every call is audited via a Log
 * row. This protects the on-disk private key from bulk exfiltration if an
 * admin session is compromised.
 */
@Injectable()
@PothosMutation()
export class BackupMutation {
  private static readonly DOWNLOAD_COOLDOWN_MS = 60 * 1000;
  private lastDownloadAt = new Map<string, number>();
  private logger = new Logger(BackupMutation.name);

  constructor(
    builder: SchemaBuilderService,
    prismaService: PrismaService,
    publisher: BackupSubscriptionPublisher,
    _backupObject: BackupObject,
    backupDiscoveryService: BackupDiscoveryService,
    backupArchiveService: BackupArchiveService,
  ) {
    const prisma = prismaService.prisma;

    // New policies start with empty operator-chosen excludes. Auto-
    // excluded resources are enforced at claim time by the worker
    // service (see BackupWorkerService.claimNextRun) using the live
    // discovery classification, so there's no need to persist them —
    // and not persisting keeps the policy in sync if the compose file
    // changes later.
    const seedDefaults = () => ({
      excludeVolumes: [] as string[],
      excludePaths: [] as string[],
    });

    const findOrCreateDefaultPolicy = async () => {
      const existing = await prisma.backupPolicy.findFirst({ orderBy: { createdAt: "asc" } });
      if (existing) return existing;
      const seeded = seedDefaults();
      return prisma.backupPolicy.create({
        data: { id: "default", enabled: false, cron: "0 2 * * *", retentionDays: 30, ...seeded },
      });
    };

    const publishPolicy = (id: string, mutation: Mutation) => publisher.publishPolicy(id, mutation);
    const publishDestination = (id: string, mutation: Mutation) => publisher.publishDestination(id, mutation);
    const publishRun = (id: string, mutation: Mutation) => publisher.publishRun(id, mutation);
    const publishKey = (id: string, mutation: Mutation) => publisher.publishKey(id, mutation);

    // --- Policy ---
    builder.mutationField("updateBackupPolicy", (t) =>
      t.prismaField({
        description: "Upsert the single BackupPolicy.",
        authScopes: { admin: true },
        type: "BackupPolicy",
        args: {
          enabled: t.arg({ type: "Boolean" }),
          cron: t.arg({ type: "String" }),
          retentionDays: t.arg({ type: "Int" }),
          excludeVolumes: t.arg({ type: ["String"] }),
          excludePaths: t.arg({ type: ["String"] }),
          excludeServices: t.arg({ type: ["String"] }),
          excludeEnvFiles: t.arg({ type: ["String"] }),
          extraEnvFiles: t.arg({ type: ["String"] }),
        },
        resolve: async (query, _root, args) => {
          const existing = await prisma.backupPolicy.findFirst({ orderBy: { createdAt: "asc" } });
          const data: Partial<BackupPolicy> = {};
          if (args.enabled != null) data.enabled = args.enabled;
          if (args.cron != null) data.cron = args.cron;
          if (args.retentionDays != null) data.retentionDays = args.retentionDays;
          if (args.excludeVolumes != null) data.excludeVolumes = args.excludeVolumes;
          if (args.excludePaths != null) data.excludePaths = args.excludePaths;
          if (args.excludeServices != null) data.excludeServices = args.excludeServices;
          if (args.excludeEnvFiles != null) data.excludeEnvFiles = args.excludeEnvFiles;
          if (args.extraEnvFiles != null) data.extraEnvFiles = args.extraEnvFiles;
          let policy;
          if (existing) {
            policy = await prisma.backupPolicy.update({ ...query, where: { id: existing.id }, data });
          } else {
            const seeded = seedDefaults();
            policy = await prisma.backupPolicy.create({
              ...query,
              data: { id: "default", enabled: false, cron: "0 2 * * *", retentionDays: 30, ...seeded, ...data },
            });
          }
          await publishPolicy(policy.id, existing ? Mutation.Updated : Mutation.Created);
          return policy;
        },
      }),
    );

    // --- Destinations ---
    builder.mutationField("createBackupDestination", (t) =>
      t.prismaField({
        description: "Create a new backup destination.",
        authScopes: { admin: true },
        type: "BackupDestination",
        args: {
          name: t.arg({ type: "String", required: true }),
          type: t.arg({ type: "BackupDestinationType", required: true }),
          output: t.arg({ type: "String" }),
          enabled: t.arg({ type: "Boolean" }),
          sseMode: t.arg({ type: "String" }),
          sseKmsKeyId: t.arg({ type: "String" }),
          order: t.arg({ type: "Int" }),
        },
        resolve: async (query, _root, args) => {
          // Local destinations target the default backup-archives volume
          // in the sidecar; output is implicit and always stored as null.
          // Other types (S3) require an operator-supplied output.
          let output: string | null = null;
          if (args.type !== "Local") {
            if (args.output == null || args.output.trim() === "") {
              throw new Error(`Destination type ${args.type} requires an output path.`);
            }
            output = args.output;
          }
          const policy = await findOrCreateDefaultPolicy();
          const dest = await prisma.backupDestination.create({
            ...query,
            data: {
              policyId: policy.id,
              name: args.name,
              type: args.type,
              output,
              enabled: args.enabled ?? true,
              sseMode: args.sseMode ?? null,
              sseKmsKeyId: args.sseKmsKeyId ?? null,
              order: args.order ?? 0,
            },
          });
          await publishDestination(dest.id, Mutation.Created);
          return dest;
        },
      }),
    );

    builder.mutationField("updateBackupDestination", (t) =>
      t.prismaField({
        description: "Update a backup destination.",
        authScopes: { admin: true },
        type: "BackupDestination",
        args: {
          id: t.arg({ type: "String", required: true }),
          name: t.arg({ type: "String" }),
          type: t.arg({ type: "BackupDestinationType" }),
          output: t.arg({ type: "String" }),
          enabled: t.arg({ type: "Boolean" }),
          sseMode: t.arg({ type: "String" }),
          sseKmsKeyId: t.arg({ type: "String" }),
          order: t.arg({ type: "Int" }),
        },
        resolve: async (query, _root, args) => {
          const data: Partial<BackupDestination> = {};
          if (args.name != null) data.name = args.name;
          if (args.type != null) data.type = args.type;
          if (args.enabled != null) data.enabled = args.enabled;
          if (args.sseMode != null) data.sseMode = args.sseMode;
          if (args.sseKmsKeyId != null) data.sseKmsKeyId = args.sseKmsKeyId;
          if (args.order != null) data.order = args.order;
          // Output handling mirrors create: Local clears it; switching to a
          // non-Local type requires a new output; otherwise pass through any
          // supplied value.
          if (args.type === "Local") {
            data.output = null;
          } else if (args.type != null) {
            if (args.output == null || args.output.trim() === "") {
              throw new Error(`Destination type ${args.type} requires an output path.`);
            }
            data.output = args.output;
          } else if (args.output != null) {
            data.output = args.output;
          }
          const dest = await prisma.backupDestination.update({ ...query, where: { id: args.id }, data });
          await publishDestination(dest.id, Mutation.Updated);
          return dest;
        },
      }),
    );

    builder.mutationField("deleteBackupDestination", (t) =>
      t.prismaField({
        description: "Delete a backup destination.",
        authScopes: { admin: true },
        type: "BackupDestination",
        args: { id: t.arg({ type: "String", required: true }) },
        resolve: async (query, _root, args) => {
          const dest = await prisma.backupDestination.delete({ ...query, where: { id: args.id } });
          await publishDestination(dest.id, Mutation.Deleted);
          return dest;
        },
      }),
    );

    // --- Runs ---
    builder.mutationField("triggerBackupRun", (t) =>
      t.prismaField({
        description: "Enqueue a manual backup run for immediate execution by the sidecar worker.",
        authScopes: { admin: true },
        type: "BackupRun",
        resolve: async (query, _root, _args, ctx) => {
          const policy = await findOrCreateDefaultPolicy();
          const inflight = await prisma.backupRun.count({
            where: { status: { in: ["Queued", "Running"] } },
          });
          if (inflight > 0) {
            throw new Error("A backup is already in progress; wait for it to finish before starting another.");
          }
          const run = await prisma.backupRun.create({
            ...query,
            data: {
              policyId: policy.id,
              status: "Queued",
              trigger: "Manual",
              requestedById: ctx?.user?.id ?? null,
            },
          });
          await publishRun(run.id, Mutation.Created);
          return run;
        },
      }),
    );

    builder.mutationField("cancelBackupRun", (t) =>
      t.prismaField({
        description: "Request cancellation of an in-flight backup run.",
        authScopes: { admin: true },
        type: "BackupRun",
        args: { id: t.arg({ type: "String", required: true }) },
        resolve: async (query, _root, args) => {
          const run = await prisma.backupRun.update({
            ...query,
            where: { id: args.id },
            data: { cancelRequested: true },
          });
          await publishRun(run.id, Mutation.Updated);
          return run;
        },
      }),
    );

    // --- Archive cleanup ---
    // Deletes the archive file at its destination (local unlink or S3
    // DeleteObject) but leaves the BackupRun / BackupRunDestination rows
    // intact so the run remains visible as an audit record. Idempotent -
    // re-invoking on an already-missing archive is a no-op.
    builder.mutationField("deleteBackupArchive", (t) =>
      t.prismaField({
        description:
          "Delete the archive file for a specific backup run destination. The DB record is retained so the run remains visible as an audit trail; only the archive file itself is removed.",
        authScopes: { admin: true },
        type: "BackupRunDestination",
        args: { runDestinationId: t.arg({ type: "String", required: true }) },
        resolve: async (query, _root, args) => {
          await backupArchiveService.deleteArchive(args.runDestinationId);
          return prisma.backupRunDestination.findUniqueOrThrow({
            ...query,
            where: { id: args.runDestinationId },
          });
        },
      }),
    );

    // --- Keys ---
    builder.mutationField("acknowledgeBackupKey", (t) =>
      t.prismaField({
        description: "Acknowledge that the backup encryption key has been securely stored offline.",
        authScopes: { admin: true },
        type: "BackupKey",
        args: { id: t.arg({ type: "String", required: true }) },
        resolve: async (query, _root, args, ctx) => {
          const key = await prisma.backupKey.update({
            ...query,
            where: { id: args.id },
            data: {
              acknowledged: true,
              acknowledgedAt: new Date(),
              acknowledgedById: ctx?.user?.id ?? null,
            },
          });
          await publishKey(key.id, Mutation.Updated);
          return key;
        },
      }),
    );

    builder.mutationField("rotateBackupKey", (t) =>
      t.prismaField({
        description:
          "Rotate the active backup encryption key. Retires the current key (sets active=false, rotatedAt=now) and lets the sidecar worker generate a fresh keypair on its next poll. The old key row is retained so historical archives remain decryptable.",
        authScopes: { admin: true },
        type: "BackupKey",
        resolve: async (query) => {
          const current = await prisma.backupKey.findFirst({ where: { active: true } });
          if (current) {
            await prisma.backupKey.update({
              where: { id: current.id },
              data: { active: false, rotatedAt: new Date() },
            });
            await publishKey(current.id, Mutation.Updated);
          }
          // The sidecar worker's ensureActiveKey() detects the missing
          // active row on its next tick, archives the on-disk private key,
          // runs init-keys.sh to generate a fresh keypair, and inserts the
          // new BackupKey row. The client will see the new row on its next
          // subscription tick; we return the most recently created row as
          // a placeholder for the mutation response.
          const latest = await prisma.backupKey.findFirst({
            ...query,
            orderBy: { createdAt: "desc" },
          });
          return latest ?? current;
        },
      }),
    );

    // --- Private key download (audited + rate limited) ---
    builder.mutationField("downloadBackupPrivateKey", (t) =>
      t.field({
        description:
          "Return the private key material for an acknowledged BackupKey. Rate limited to one call per minute per user and audited via the Log service.",
        authScopes: { admin: true },
        type: "String",
        args: { id: t.arg({ type: "String", required: true }) },
        resolve: async (_root, args, ctx) => {
          const userId: string = ctx?.user?.id ?? "anonymous";
          const now = Date.now();
          const last = this.lastDownloadAt.get(userId) ?? 0;
          if (now - last < BackupMutation.DOWNLOAD_COOLDOWN_MS) {
            throw new Error("Please wait before downloading the backup private key again.");
          }
          this.lastDownloadAt.set(userId, now);

          const key = await prisma.backupKey.findUniqueOrThrow({ where: { id: args.id } });
          if (!key.acknowledged) {
            throw new Error("You must acknowledge the key before downloading it.");
          }

          // Audit the download through the application logger so the event
          // flows into the normal log pipeline (console + Log table via
          // PrismaLogger). Do NOT write to the `Log` table directly from
          // domain code — that table is owned by the logging subsystem.
          this.logger.warn(
            `Backup private key downloaded: userId=${userId} keyId=${key.id} fingerprint=${key.fingerprint}`,
            BackupMutation.name,
          );

          // The worker is expected to populate `privateKeyPath` on the row.
          // If it is missing we refuse the download rather than silently
          // returning nothing.
          const fs = await import("fs/promises");
          if (!key.privateKeyPath) {
            throw new Error("Private key material is not available for this key.");
          }
          return fs.readFile(key.privateKeyPath, "utf-8");
        },
      }),
    );
  }
}
