
[tool.ruff]
line-length = 120
target-version = "py310"
extend-select = ["E", "F", "I"]


[project]
name = "aems-edge"
version = "0.1.0"
description = "AEMS Edge project."
dependencies = [
	"pandas",
	"aems-lib-fastapi @ file://../aems-lib-fastapi",
	"volttron-core"
]
