[tool.yapfignore]
ignore_patterns = [
    ".pytest_cache/**",
    "dist/**",
    "docs/**",
    "build/**",
    "dist/**"
]

[tool.yapf]
based_on_style = "pep8"
spaces_before_comment = 4
column_limit = 120
split_before_logical_operator = true
