{
 "title": "RTU Overview",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "RTU_ROB", "query": "select topic_name from topics" }
  ]
 },
 "panels": [
  {
   "title": "Zone Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"Zone Temperature\" from data natural join topics where topic_name like 'PNNL/ROB/%' and topic_name like '%/$RTU_ROB/ZoneTemperature' AND $__timeFilter(ts) ORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Zone Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"ZoneHumidity\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU_ROB/ZoneHumidity' AND $__timeFilter(ts) ORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Outdoor Air Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"OutdoorAirTemperature\" from data natural join topics where topic_name like 'PNNL/ROB/%/OutdoorAirTemperature' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Heating Setpoint",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"Heating SP\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU_ROB/OccupiedHeatingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Cooling Setpoint",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"Cooling SP\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU_ROB/OccupiedCoolingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Heating Command",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"Heating Command\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU_ROB/FirstStageHeating' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Supply Fan",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"Supply Fan\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU_ROB/SupplyFanStatus' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Occupancy Command",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"Occupancy\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU_ROB/OccupancyCommand' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Cooling Stage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(ts, '1m') AS \"time\",\n  SUM(CAST(value_string AS DOUBLE PRECISION)) AS \"CoolingStage\"\nFROM data\nNATURAL JOIN topics\nWHERE topic_name LIKE 'PNNL/ROB/$RTU_ROB/%StageCooling'\n  AND $__timeFilter(ts)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "$RTU_ROB",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"OccupiedCoolingSetPoint\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU_ROB/OccupiedCoolingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"OccupiedHeatingSetPoint\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU_ROB/OccupiedHeatingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"FirstStageHeating\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU_ROB/FirstStageHeating' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"SupplyFanStatus\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU_ROB/SupplyFanStatus' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"ZoneHumidity\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU_ROB/ZoneHumidity' AND $__timeFilter(ts) ORDER BY 1;\r\n"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"ZoneTemperature\" from data natural join topics where topic_name like 'PNNL/ROB/%' and topic_name like '%/$RTU_ROB/ZoneTemperature' AND $__timeFilter(ts) ORDER BY 1;\r\n"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"OutdoorAirTemperature\" from data natural join topics where topic_name like 'PNNL/ROB/%/OutdoorAirTemperature' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"OccupancyCommand\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU_ROB/OccupancyCommand' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroup(ts, '1m') AS \"time\",\r\n  SUM(CAST(value_string AS DOUBLE PRECISION)) AS \"CoolingStage\"\r\nFROM data\r\nNATURAL JOIN topics\r\nWHERE topic_name LIKE 'PNNL/ROB/$RTU_ROB/%StageCooling'\r\n  AND $__timeFilter(ts)\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"UnoccupiedCoolingSetPoint\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU_ROB/UnoccupiedCoolingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"UnoccupiedHeatingSetPoint\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU_ROB/UnoccupiedHeatingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  }
 ]
}